# -*- coding: utf-8 -*-

##
## How to install all gems:
##
##     $ mkdir gems                       # if necessary
##     $ export GEM_HOME=$PWD/gems        # if necessary
##     $ export PATH=$GEM_HOME/bin:$PATH  # if necessary
##     $ gem install bundler              # if necessary
##     $ bundler install
##

source 'https://rubygems.org'

gem 'rack'                , '~> 1.6'
gem 'rack-test_app'       , '~> 1.0'
gem 'keight'              , '~> 0.2'
gem 'baby_erubis'         , '~> 2.1.1'
gem 'minitest'            , '~> 5.4'
gem 'minitest-ok'         , '~> 0.1'
