# -*- coding: utf-8 -*-

#require "bundler/gem_tasks"

#require 'rake/testtask'
#Rake::TestTask.new(:test) do |t|
#  t.libs << "test"
#  t.test_files = FileList['test/**/*_test.rb']
#  #t.verbose = true
#end

desc "run test scripts"
task :test do
  files = [
    './test/**/*_test.rb',
  ]
  code = 'ARGV.each {|p| Dir.glob(p).each {|f| require f } }'
  system("ruby -v")
  system("ruby", "-e", code, *files)
end

task :default => :test
